//get all domain
export const GET_ALL_DOMAIN_REQUEST = 'GET_ALL_DOMAIN_REQUEST';
export const GET_ALL_DOMAIN_SUCCESS = 'GET_ALL_DOMAIN_SUCCESS';
export const GET_ALL_DOMAIN_FAILE = 'GET_ALL_DOMAIN_FAILE';

export const UPDATE_DOMAIN_REQUEST = 'UPDATE_DOMAIN_REQUEST';
export const UPDATE_DOMAIN_SUCCESS = 'UPDATE_DOMAIN_SUCCESS';
export const UPDATE_DOMAIN_FAILE = 'UPDATE_DOMAIN_FAILE';

export const DELETE_DOMAIN_REQUEST = 'DELETE_DOMAIN_REQUEST';
export const DELETE_DOMAIN_SUCCESS = 'DELETE_DOMAIN_SUCCESS';
export const DELETE_DOMAIN_FAILE = 'DELETE_DOMAIN_FAILE';

export const ADD_DOMAIN_REQUEST = 'ADD_DOMAIN_REQUEST';
export const ADD_DOMAIN_SUCCESS = 'ADD_DOMAIN_SUCCESS';
export const ADD_DOMAIN_FAILE = 'ADD_DOMAIN_FAILE';


export const SCAN_DOMAIN_REQUEST = 'SCAN_DOMAIN_REQUEST';
export const SCAN_DOMAIN_SUCCESS = 'SCAN_DOMAIN_SUCCESS';
export const SCAN_DOMAIN_FAILE = 'SCAN_DOMAIN_FAILE';

export const SCAN_DOMAIN_FAILE_UPDATE_STATUS = 'SCAN_DOMAIN_FAILE_UPDATE_STATUS';


export const GET_ALL_TELEGRAM_REQUEST = 'GET_ALL_TELEGRAM_REQUEST';
export const GET_ALL_TELEGRAM_SUCCESS = 'GET_ALL_TELEGRAM_SUCCESS';
export const GET_ALL_TELEGRAM_FAILE = 'GET_ALL_TELEGRAM_FAILE';

export const UPDATE_TELEGRAM_REQUEST = 'UPDATE_TELEGRAM_REQUEST';
export const UPDATE_TELEGRAM_SUCCESS = 'UPDATE_TELEGRAM_SUCCESS';
export const UPDATE_TELEGRAM_FAILE = 'UPDATE_TELEGRAM_FAILE';

export const DELETE_TELEGRAM_REQUEST = 'DELETE_TELEGRAM_REQUEST';
export const DELETE_TELEGRAM_SUCCESS = 'DELETE_TELEGRAM_SUCCESS';
export const DELETE_TELEGRAM_FAILE = 'DELETE_TELEGRAM_FAILE';

export const ADD_TELEGRAM_REQUEST = 'ADD_TELEGRAM_REQUEST';
export const ADD_TELEGRAM_SUCCESS = 'ADD_TELEGRAM_SUCCESS';
export const ADD_TELEGRAM_FAILE = 'ADD_TELEGRAM_FAILE';
